apiVersion: v1
kind: Pod
metadata:
  name: podconfig
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort:
      envFrom:
        - configMapRef:
            name: configmap
