apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  username: "YMRtaW4K"
  password: "YWRtaW4xMjMK"

---
apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
    - name: nginx
      image: nginx
