apiVersion: v1
kind: Pod
metadata:
  name: clusterpod
  labels:
    name: frontend
		project: expense
		environment: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2

---

apiVersion: v1
kind: Service
metadata:
  name: clusterip
spec:
  selector:
    name: frontend
		project: expense
		environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80