kind: Pod
apiVersion: v1
metadata:
	name: clusterpod
	labels:
		name: frontend
		project: expense
		environment: dev
spec:
	containers:
	- name: nginx
	  image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: clusterip
spec:
  selector:
    name: frontend
		project: expense
		environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80